application-description: @project.description@
application-version: @project.version@

app:
  jwt-secret: 90c8c2c617816e6a2afe2c4ed8abcfeed5144a0d73a39648df3228690b64f45e
  jwt-expiration-milliseconds: 604800000
#jwt:
#  secretKey: secret
#  issuer: ${JWT_ISSUER:https://github.com/rimmelasghar}
#  expirationMinute: 10

swagger:
  contact-name: Filip VE
  contact-mail: ${SWAGGER_CONTACT_MAIL:filipve@email.com}
  contact-url: ${SWAGGER_CONTACT_URL:https://filipve.com}
  app-name: ${SWAGGER_APP_NAME:Spring Boot Boilerplate Project}
  app-description: "Spring Boot Boilerplate is a starter kit for developing production ready SpringBoot Applications. This project includes : Spring Boot(3.1.2), Spring Data JPA, Spring Validation, Spring Security + JWT Token, MySQL, Mapstruct, Lombok, Swagger "
  app-version: ${SWAGGER_APP_VERSION:2.0.0}
  app-license-url: ${SWAGGER_APP_LICENSE_URL:https://www.apache.org/licenses/LICENSE-2.0.html}
  app-license: ${SWAGGER_APP_LICENSE:Apache 2.0}