server:
  address: localhost
  # Random/Dynamic Port:
  # port: 0
  # Random port in a custom predefined range:
  port: ${random.int(8020,8030)}
#  port: 8080
  compression:
    enabled: true
  error:
    include-message: always
  forward-headers-strategy: framework

spring:
  application:
    name: springbootmavenstartertemplate
  profiles:
    active: customproperties, springdoc
  liquibase:
    enabled: false # default turning liquibase off


logging:
  level:
    org.springframework: INFO
    org.fve: INFO