spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:mydatabase}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: ${MYSQL_USER:myuser}
    password: ${MYSQL_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: create-drop
#      naming:
##        implicit-strategy:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl